Iter5
romanyakovlev/go-yandex-url-shortener pull request #5
Opened 2024-03-12 14:54 UTC by romanyakovlev

2024-03-13 14:15 UTC, arttet requested changes
Please add
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/config.go
> +var flagAAddr string
CHANGE REQUEST: please don't use global variables

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/config.go
> +package main
CHANGE REQUEST: please update Go layouts
https://github.com/golang-standards/project-layout

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/main.go
> +		panic(err)
CHANGE REQUEST: please don't use `panic`

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/server.go
> +func saveURL(shortener URLShortener, w http.ResponseWriter, r *http.Request) {
CHANGE REQUEST: it should be a method

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/server.go
> +func URLShortenerRouter(shortener URLShortener) chi.Router {
```suggestion
func Router(shortener URLShortener) chi.Router {
```

2024-03-13 14:15 UTC, arttet commented on cmd/shortener/service.go
> +import (
CHANGE REQUEST: please format your code

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/config.go
> +var flagAAddr string
done

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/config.go
> +package main
done

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/main.go
> +		panic(err)
done

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/server.go
> +func saveURL(shortener URLShortener, w http.ResponseWriter, r *http.Request) {
done

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/server.go
> +func URLShortenerRouter(shortener URLShortener) chi.Router {
done

2024-03-18 07:51 UTC, romanyakovlev commented on cmd/shortener/service.go
> +import (
done

2024-03-18 14:30 UTC, arttet approved these changes

2024-03-18 16:02 UTC, merged